<?php

namespace AppBundle\Repository;

use AppBundle\Entity\ChessMatch;
use Doctrine\ORM\EntityRepository;
use Doctrine\ORM\Query\Lexer;
use Doctrine\ORM\Query\AST\Functions\FunctionNode;

/**
 * ChessMatchRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ChessMatchRepository extends EntityRepository
{
    /**
     * @param $id
     * @return ChessMatch[]
     */
    public function findMatchesByPlayer($id)
    {
        $query = $this->getEntityManager()
            ->createQuery(
                'SELECT c, p FROM AppBundle:ChessMatch c
        JOIN c.player p
        WHERE p.id = :id'
            )->setParameter('id', $id);

        try {
            return $query->getResult();
        } catch (\Doctrine\ORM\NoResultException $exception) {
            return null;
        }
    }

    /**
     * @param $min_date
     * @param $max_date
     * @return ChessMatch[]
     */
    public function findMatchesByDate($min_date, $max_date)
    {
        return $this->createQueryBuilder('m')
            ->andWhere('m.start >= :min_date')
            ->andWhere('m.start <= :max_date')
            ->setParameter('min_date', $min_date)
            ->setParameter('max_date', $max_date)
            ->getQuery()
            ->execute();
    }
}
