<?php

namespace AppBundle\Repository;

/**
 * ChessMatchRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ChessMatchRepository extends \Doctrine\ORM\EntityRepository
{
}
