<?php

namespace AppBundle\Repository;

use AppBundle\Entity\ChessMatch;
use Doctrine\ORM\EntityRepository;

/**
 * ChessMatchRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ChessMatchRepository extends EntityRepository
{
    /**
     * @return ChessMatch[]
     */
    public function findMatchesByPlayer($id)
    {
        $query = $this->getEntityManager()
            ->createQuery(
                'SELECT c, p FROM AppBundle:ChessMatch c
        JOIN c.player p
        WHERE p.id = :id'
            )->setParameter('id', $id);

        try {
            return $query->getResult();
        } catch (\Doctrine\ORM\NoResultException $exception) {
            return null;
        }
    }
}
