<?php

namespace AppBundle\Repository;

/**
 * PlayearsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PlayearsRepository extends \Doctrine\ORM\EntityRepository
{
}
