<?php

namespace AppBundle\Repository;

use AppBundle\Entity\Players;
use Doctrine\ORM\EntityRepository;

/**
 * PlayersRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PlayersRepository extends EntityRepository
{
    /**
     * @return Players[]
     */
    public function findPlayerRating($id)
    {
        return $this->createQueryBuilder('players')
            ->andWhere('players.id ='. $id)
            ->getQuery()
            ->execute();
    }
}
